import { ReactElement } from "react";
import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
import { LoginLayout } from "../components/layouts/login";
import { LoginForm } from "../components/auth";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>MusicThing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginForm />
    </>
  );
};

Home.getLayout = (page: ReactElement) => <LoginLayout>{page}</LoginLayout>;

export default Home;
